#release configuration
#Tue Sep 08 14:07:39 EDT 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.net.preibisch\:BigStitcher=3.0.10-SNAPSHOT
project.rel.net.preibisch\:BigStitcher=3.0.9
project.scm.net.preibisch\:BigStitcher.connection=scm\:git\:https\://github.com/JaneliaSciComp/BigStitcher
project.scm.net.preibisch\:BigStitcher.developerConnection=scm\:git\:git@github.com\:JaneliaSciComp/BigStitcher
project.scm.net.preibisch\:BigStitcher.tag=HEAD
project.scm.net.preibisch\:BigStitcher.url=https\://github.com/JaneliaSciComp/BigStitcher
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=BigStitcher-3.0.9
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/JaneliaSciComp/BigStitcher
